all: producer  consumer init zad2 licz

przykl: przykl.c
	gcc przykl.c -o przykl -lrt

producer: producer.c
	gcc producer.c -o producer -lrt
consumer: consumer.c
	gcc consumer.c -o consumer -lrt

licz: licz.c
	gcc licz.c -o licz -lrt
	
zad2: zad2.c
	gcc zad2.c -o zad2 -lrt
